name = "Big Globe With Create"
author = "pluumenbrownie"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f22be87e539f2354a3c4eb281e6062d71cbca07381b79ff36d67d3b2efc84af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
datapack-folder = "config/paxi/datapacks"
