name = "Big Globe With Create"
author = "pluumenbrownie"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9a5490903d7caa068214da6ead4e9db6cb700d67ada0ec935b531e1d6f99449"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
datapack-folder = "config/paxi/datapacks"
