name: Build Repository Pages

run-name: Building and publishing new repository pages.

on: 
  push:
    branches: [$default-branch]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: create test site
        run: |
          mkdir output
          echo "testing" > output/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './output'
        
        
